### ISSUE TITLE
配信環境

### ISSUE THREAD

**Issue by kkotaro0111** [uzulla/y8-2017-spring#14]
機材とか配信先とか構図とか

**Comment by kkotaro0111** [comment]
【配信先】
ヤッパチのYouTubeチャンネルあるし、YouTubeLiveでいいんじゃね？

**Comment by uzulla** [comment]
Youtube Liveいいんじゃないですかね。そのままストアできるし、とりまわしやすいし。
というか、他にこの用途に向いたいい対抗馬はいまいるのだろうかｗ

**Comment by uzulla** [comment]
![image](https://cloud.githubusercontent.com/assets/870716/23618511/ddb9c3fe-02d3-11e7-9e4d-3b6695eb48f0.png)

**Comment by kkotaro0111** [comment]
うーん、Facebookかなぁ。
たぶん界隈的に、YouTubeよりかはリーチ力高い（それが重要かどうかは別）

**Comment by uzulla** [comment]
たしかにFBはみんな見てくれるし、Youtubeよりはチャットがいいね（YTのチャットはひどいｗ）
ただ、FBとかつかーねーよ！って人が多いからな…

**Comment by kkotaro0111** [comment]
配信用にLiveShellをレンタルとかするなら、マルチ配信も可能だし、片っ端から投げられるけど、俺の知見が溜まる以上のメリットがあまりない。
とりま、YouTubeでいきましょう。

**Comment by kkotaro0111** [comment]
構図案
- スライドと登壇者は別撮り
    - PinP？ side by side？
    - スライドはミラーリングで取りたい
    - 構成の規模が大きくなりがち（気を使うところが増え、機材トラブル率が上がる）
    - スライド外でデモする人に対応しにくい
- 去年の録画と似た構図で一括撮り
    - スライド見にくい
    - 配信としての面白みがあまりない
    - 懸念事項が少なくなるので、ある程度自由が効く
- マルチカメラにスイッチャー
    - 登壇者の横顔とかかっこいい
    - どうせ下見て話す人多いだろうから、その先にも一個カメラ置いてやろうか
    - 懸念事項も増え、とにかく大変
    - たーのしー！

**Comment by uzulla** [comment]
マルチとかはすきにやってもらってよいです、知見ためて下さい。
別に失敗（？）してもいいです。

**Comment by kkotaro0111** [comment]
@uzulla 会場の間取りとか広さとかってわかりますか？
あと、スライドをミラーリングするのに、会場自体にそういう設備があるのか、それとも分配器のようなものを自分で用意する必要があるのか等々、必要機材のリストアップに必要そうな情報が欲しいです。

**Comment by uzulla** [comment]
会場の部屋は色々あってまだ拝見できていません。進捗あったらまた連絡します。

ただ、VGAスプリッタが完備された会場ってなかなかレアなので、それをやりたいなら分配器はないと厳しいんじゃないかなあ（まだHDMIなのか、VGAなのかもわからないですが

**Comment by uzulla** [comment]
## 会場の間取りと広さ

https://photos.google.com/share/AF1QipM3J46UprF_LCyC4qMsNU4TO-yWfH_hVsiRbv13zY-lQaS2CSclO33lz46ZZ5iRzA?key=V2wzUkswYnhsRHlsT09IT1dKZDVBSG9nQlhyWDVn

## 映像

映像はHDMIでした
（取り出せる）スプリッタっぽいものはなかったです、必要なら別途。

## 回線

電源はあります、無線LANは速度がどれくらいでるかはなんとも言えない感じです。
（ただ、APはそれなりに打ってあるので、ちゃんとしてるとは思います）

**Comment by kkotaro0111** [comment]
ありがとうございます

すでにHDMIスプリッタを手配済みです
いかがわしいやつなので、壊れてないことを祈ります

回線について、有線を利用することは無理っぽいですか？

**Comment by uzulla** [comment]
残念ながら有線はどこにも出てないですね、無線LANは天井に敷設されたものなので、そこらにポートがあるという環境ではないです。

**Comment by uzulla** [comment]
まあ、リアルタイム配信はあんまり重要ではないんで。

エンコーダー設定ができるなら、FPSを落として720pで十分、音声はモノラル64kbpsとかでよいです。
（録画も、720iで大抵大丈夫です）

**Comment by uzulla** [comment]
http://speedify.com/desktop-vpn/
あとは、こーいうの使うかねえ。

**Comment by kkotaro0111** [comment]
間取りについて、
登壇台から、一番後ろの席までの距離ってわかります？
テーブルが7列あって、１列あたり1.5mくらいかなぁと考えると、
テーブル部分だけで10m超くらいなのかな

**Comment by uzulla** [comment]
すみませんが写真で想像してください！
すごく精度がいらないならですが。

**Comment by kkotaro0111** [comment]
とりま15m想定で、20mのHDMIあれば1本でいけるかな。

**Comment by kkotaro0111** [comment]
# 配信環境図
https://cacoo.com/diagrams/uezmX78qWqW2r7Jj

# 機材
- HDMIケーブル 20m x 1 （川嶋購入済み）
  - イコライザ付きのため、専用電源アダプタ有
- HDMIケーブル 1m x 5 （川嶋たぶん余ってる）
  - 配信用カメラ -> LiveWedge
  - 録画用カメラ -> LiveWedge
  - LiveWedge -> プレビューモニタ
  - LiveWedge -> プログラムモニタ
  - 発表用PC -> HDMIスプリッタ
- Mac<->HDMIアダプタ x 1 （川嶋提供 / pastak氏提供）
- PC<->HDMIアダプタ x 1 （ papix氏提供 / hasegawa-tomoki氏提供）
- HDMIスプリッタ x 1 （川嶋購入済み）
- LiveWedge （レンタルサービス利用）
  - SDカード内にロゴファイルを入れておく （非配信用）
  - SDカード内にウォーターマークを入れておく（Dashboardから追加できるっぽい）
  - 配信ダメな人向けの閑話休題的なダミー映像欲しいかも
- iPad （LiveWedge操作用）（川嶋私物）
- iPhone （セッション間等でながすBGM）
- Mac （配信確認等）（川嶋私物）
- NinjaAssassin （LiveWedgeのプログラムモニタ代わり）（川嶋私物）
- 何かモニタ （LiveWedgeのプレビューモニタ代わり）（提供未定）
- ワイヤレスマイク （登壇者音声用）
- 録画用ハンディカム（登壇者音声入力兼用）
  - 要三脚
- 配信用カメラ（川嶋私物）
  - 要三脚

## 電源が必要な機材
### 登壇者側（AC-3/USB-1）
- HDMIスプリッタ（AC）
- 発表用PC（AC）
- USBチャージャー（AC）
- HDMI電源アダプタ（イコライザ用 / USB）
### 配信側（AC-7/USB-3）
- LiveWedge（AC）
- 録画用ハンディカム（AC）
- 配信用カメラ（AC）
- Mac（AC）
- NinjaAssassin（AC）
- プレビュー用モニタ （AC）
- USBチャージャー（AC）
- iPad（USB）
- iPhone （BGM用 / USB）
- iPhone （私用 / USB）

# 懸念点
- どの機材も、連続動作可能時間が不明
  - 熱暴走的な意味で。
  - ワイヤレスマイクは、単4電池x1 で 2時間程度動作

**Comment by uzulla** [comment]
すごい本格的だ、これは後世のためにブログにしよう。

**Comment by kkotaro0111** [comment]
LiveWedgeの機器レンタル予約は完了した

**Comment by uzulla** [comment]
@kkotaro0111 

物品上にリストされているけど、不足してるものとかそういうのがわからないので、不足のものを不足ってかいて募ってもらえるとたすかります。
あと、電源ケーブルはどうします？

どうしても不足しているものは買いますので何卒。

**Comment by uzulla** [comment]
@kkotaro0111 

HDMIのモニタと、カメラと三脚、あとは電源ケーブルをもってけばいいのかな？
BGM用iPhoneはアテあります？一応iPhoneあるけど、アプリどうしますかね
ワイヤレスマイク （登壇者音声用）はあるんでしたっけ？

**Comment by kkotaro0111** [comment]
@uzulla 
下記のもの以外は、こちらで準備できています。

# 不足
- HDMIのモニタ
- 電源ケーブル
- 三脚

# 予備としてあるといい
- カメラ
- HDMIケーブル

**Comment by uzulla** [comment]
@kkotaro0111 

- HDMIモニタ - 入手してもっていきます > HDMI 入力できるモニタ買った
- 電源ケーブル ヤパチでつかった長いやつx2＋、タップを持っていきます（重い 
- 三脚 > 持ってるやつを持っていく 
- カメラ > ハンディカムだよね？CX670もっていきます

- HDMIケーブル > タイプがわからない… ＞ フルサイズHDMI＜＞フルサイズ フルサイズ＜＞マイクロを持っていくことにした

**Comment by kkotaro0111** [comment]
- カメラ > ハンディカムですかね。 一応、使う予定のものは用意できてるので、あくまで予備という位置づけです。
- HDMIケーブル > フルサイズ<>フルサイズでOKです。これも数は用意できてるので、あくまで予備という感じです。

**Comment by uzulla** [comment]
配信システムエントリも書いていただいたので、これにてクローズ

http://vook.vc/n/315
