### ISSUE TITLE
イベントの方向性とかについてスレ

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#2]
# 方向性とは？

そこまでしばる気はないけど、去年のya8cとは規模が違うので（１トラック１日なので）、ある程度方向性をみせてもよいかなとおもう。

住み分けもあるし、発表初心者でも参加できるようなものがのぞましい。半分くらいはあまり発表したことがない人にしたい。
（とはいえ、歴戦の戦士を排除したいわけではなく、気後れしないでほしい）

# だれが開催するのか

uzullaの趣味です

ただ、builderscon方面のシステムを使おうかなと思っている（手間と相談）

# どこで開催するのか

会場はきまっている、渋谷です。5/27(土)。

# 初心者でも参加できる案がほしい

を少し用意したい。たとえば「こういうトークがいいんじゃない！？」みたいな助け舟とか、「良いプロポーザルの書き方」とか。

・つくってるもの発表
・ワンイシューの解決
みたいな

逆に「これは（大抵）ウケないよ」ということを教えてあげたい 

・会社や仕事の紹介、自分語り（でも、これ一番簡単なんだよな）
・（そこらのブログにかかれていそうな感じの）やってみました

なお、発表時間は短めにする予定、ちゃんと練習してもらいたいから。

昔かいたけど、今回も発表者をサポートするコンテンツがほしいな

http://ltthon-yapc2012.hachiojipm.org/howto2.html
http://yapcasia8oji-2016mid.hachiojipm.org/2016/06/11/for-beginner-talker/

**Comment by papix** [comment]
> 発表初心者でも参加できるようなものがのぞましい

というの, めっちゃいいと思いました. なので, ｢カンファレンス登壇未経験者枠｣とかあるといいのかな, って思いました!

**Comment by uzulla** [comment]
🈴

**Comment by motchang** [comment]
「トークの振返りがセットになっている枠」を一案として。
トークのリアクションで忌憚のない評価が返ってくることは、社内/仲間内以外ですとあまりないかと思いますので、やってみるのも面白いのではないかと。
想定は2,3回発表をしたことがある人という感じでしょうか？

**Comment by hasegawa-tomoki** [comment]
プラスで、発表前に資料を添削してあげる、というのが付くと
良いんじゃないかという気がします。うえしーみてると。（やぱちー
前に結構添削した。）

**Comment by hasegawa-tomoki** [comment]
とか書いたらSlackですでにそう言う話してた。
トークコンサル良いと思います！

**Comment by mass10** [comment]
座談会(オープンスペース？アンカンファレンス？)とか

**Comment by uzulla** [comment]
座談会的なの、今回狭いから無理だけど、いつかはやってみたいですね（うまくいったケースをあんまみたことがないマン）

**Comment by uzulla** [comment]
「トーク応募になぜおちたのかおしえてくれる」というベリーハードモードな意見をみました。

**Comment by hasegawa-tomoki** [comment]
ほとんどが「おもしろそうじゃないから」になりそうだなー

**Comment by uzulla** [comment]
「面白そうか」というのは完全に結果なので、分解できないならまあ意味はないですね…

**Comment by hasegawa-tomoki** [comment]
確かに。なぜ面白そうに見えないかを教えてあげられれば最高なんですね。

**Comment by uzulla** [comment]
http://y8-2017-spring.hachiojipm.org/2017/03/07/recent-status/
とりあえず、ここに書いた範囲で落ちとします。

案外初心者というものはいらっしゃらないし、サポートして〜という人は一切いなかった。学びがある。
