### ISSUE TITLE
HDMI<->DisplayPort、HDMI<->usb-cの変換の用意

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#20]
誰かにお借りできないか探す（いなければ買う）

> 今回VGAでないのもちゃんと告知しないとな

- [x] HDMI → kkotaro0111提供
- [x] USB-C → pasta-k提供

**Comment by kkotaro0111** [comment]
HDMI<->DisplayPort
これでよければ。
![2017-04-04 22 58 29](https://cloud.githubusercontent.com/assets/1256392/24660369/4a83be3c-198a-11e7-91a5-3ed93d2a18cc.jpg)

**Comment by uzulla** [comment]
よさそう！お願いできますか。

**Comment by kkotaro0111** [comment]
了解です
壊れないことを祈っててください←

**Comment by uzulla** [comment]
まあ前日くらいに可能ならチェックしてくれれば…。
こわれたら近所のヤマダ電機かビックカメラにダッシュということで（）

**Comment by kkotaro0111** [comment]
Windows/Linuxユーザー向けに、USB<->HDMIもあった方が良いかもしれない。

**Comment by uzulla** [comment]
ドライバがいらないやつでいいやつがあるのだろうか

**Comment by pastak** [comment]
Type-C -> HDMIのやつあります。

Appleの純正のやつです。

**Comment by uzulla** [comment]
もしよければお借りしたい！

**Comment by pastak** [comment]
もちろん！！

**Comment by papix** [comment]
> Windows/Linuxユーザー向けに、USB<->HDMIもあった方が良いかもしれない。

ドライバなしで使えるものはなかったような...
とはいえ, あれのドライバ, 機種が違ってもだいたい共通のものを使っているので, 念のために置いておいてもいいかもしれません.

ちなみにUSB<->HDMIの変換するやつ, 1つ余っているはずなので, 念の為置いておきたいのであればお貸しします.

**Comment by uzulla** [comment]
@papix 

じゃあお借りしたい
…と言って、当日papix氏これないんだよね？微妙かな。

**Comment by hasegawa-tomoki** [comment]
ドライバ必要だけど自分も持ってます。
DisplayLinkのやつ。
https://www.amazon.co.jp/gp/product/B018YHMMQ0

**Comment by uzulla** [comment]
@hasegawa-tomoki 

ありがとうございます、一応お借りできますか？
ただまあ、個人的にはドライバまでいれてもらうUSB＜＞HDMIはToo muchだとおもっていて、
（「世の中にはいれないやつがある」という意味ではない。PC貸したほうが早い的な意味で）
準備も考えるとよほどのことがなければ…という感想ですが。

**Comment by papix** [comment]
> …と言って、当日papix氏これないんだよね？微妙かな。

えと, 夕方辺りから所要があるので, 会場設営〜15:00くらいまで(邪魔でなければ)お手伝いしたい, という気持ちであります(スタッフスレ書いてなかった!!! 🙇 ).
なので, 朝お渡しして, 当面使う予定もないモノなので, 適当にはちぴーの際などお渡し頂ければ... という感じです.

**Comment by uzulla** [comment]
@papix 

有難うございます！ぜひお手伝い願います！（まあ、今回設営ほとんどないんですけどｗ）

> USB-HDMI
とりあえずはせがわさんからお借り出来そうなので、大丈夫です！有難うございます

**Comment by uzulla** [comment]
とりあえずクローズしておく
