### ISSUE TITLE
キックオフ:beer:

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#22]

**Comment by uzulla** [comment]
第一回決起集会を開きたいのだが、だれか調整さんと幹事をやってくれないだろうか…。

**Comment by motchang** [comment]
このチケットまだ生きていればやりまあす！

**Comment by uzulla** [comment]
絶賛生きてます！！！

**Comment by uzulla** [comment]
どうかなあ、調整さん位たてる？

**Comment by uzulla** [comment]
https://chouseisan.com/s?h=3a3de44efa5d428d917281b87ef8233f
5/11(木) 20:00〜が一番イイ感じである。

**Comment by uzulla** [comment]
予約しました。

https://www.hotpepper.jp/strJ001127934/
2時間飲み放題付『料理長おまかせコース』2980円⇒2500円(税込)
ご来店日時    2017年05月17日（水） 20時00分
予約はイシダ

**Comment by uzulla** [comment]
無事終了した。
