### ISSUE TITLE
司会のスクリプトを用意する

### ISSUE THREAD

**Issue by motchang** [uzulla/y8-2017-spring#32]
- 3枚
- 去年のコピペ
- ベストトークへの誘導が追記されているとよい

**Comment by motchang** [comment]
ref #31

**Comment by papix** [comment]
｢次のトークは○○さんの✕✕✕です.｣的な司会をするのであれば, 登壇者のお名前(ID)について, どうお呼びすればよいか事前に確認しておくと良さそう.

**Comment by makamaka** [comment]
papixさんの作ってくださったものを追加・修正しました。 ぱぴさんありがとうございます！

# 司会のスクリプト

## トーク開始時

｢時間となりましたので始めさせて頂きます. ○○(発表者のお名前)さんによる, ××(トークタイトル)です. それではよろしくお願いいたします. 皆さん拍手をお願いします｣


※発表者のお名前(ID)や, トークタイトルで読み方が分からないところがあれば, 発表前に確認しておく

## トーク終了時

｢ありがとうございました. 皆さん拍手をお願い致します」

* 時間が残っていれば
  * 「質問や感想があれば挙手をお願いします」
* 時間になったら
  * 「それでは時間となりましたのでこれにて本トークは終了となります. 最後にもう一度〇〇さんに拍手をお願いします｣


「ぜひベストトークの投票をお願いします. Y8サイトから投票ページへのリンクがあります. 良かったと思うトークにチェックを入れてください. チェックはいくつでも入れられます」

https://y8-2017-spring.motchang.com/

## 11:40～12:00のトーク終了時

（「トーク終了時」の後に）
「これより1時間の休憩になります. 次のトークは13時からです」

## 17:50～18:00のトーク終了時

（「トーク終了時」の後に）
「これで全てのトークが終わりました. 10分の休憩を挟んで閉会式になります. まだベストトークの投票がお済でない方は、ぜひ投票をお願いします. Y8サイトのタイムテーブルページから投票ページへのリンクがあります. 良かったと思うトークにチェックを入れてください. チェックはいくつでも入れられます」

**Comment by makamaka** [comment]
これで問題なければ3部印刷していきます。
