### ISSUE TITLE
「Y8 2017 spring」とかかれた紙数枚

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#33]
最初のうち、人の誘導に使う為

**Comment by uzulla** [comment]
@makamaka

お手数ですが、こちらもお願いできますか？
画像は
https://github.com/uzulla/y8-2017-spring/tree/master/images/logo/png%402x
ここらへんを印刷していただければ…。

**Comment by makamaka** [comment]
了解ですー
