### ISSUE TITLE
懇親会の会費徴収

### ISSUE THREAD

**Issue by keima** [uzulla/y8-2017-spring#35]
https://connpass.com/event/56654/
http://y8-2017-spring.hachiojipm.org/time-table/

## 誰がやるのか

しんぺいさん @Shinpeim  と ワシ @keima

## なにをするのか

- 現地（懇親会会場）でひとりあたり ￥3000 もらう
  - 現地以外（例えばマークシティ17階）では集金したくないなぁみたいな気持ちある
  - ~~TODO: 受付票チェックする？~~
  - 申込者のcsvを2部印刷し、代金をもらったら✓つけます。
    - 最後に2部のチェック状態をマージして付き合わせ。
  - ~~TODO: 当日やっぱり来ちゃった///みたいな人の対応。~~
  - 当日参加者はcsv用紙の余白に記録

## ほかになにをするのか

- 懇親会開催前に現地に先乗りして作業
  - そもそも会場が存在するか確認
  - 机とイスを借りるとかして集金場所の確保
- お釣りはあらかじめ用意しない、スタッフがみんな千円札で払えば充分やろ（圧）

## タイムスケジュール

TODO: 18:00 - 22:00 あたりまでの大雑把な予定を考える

## メモ

- 懇親会の一部時間でしんぺいさんが登壇するのでその間ワンオペ。まぁいけるやろ。

**Comment by Shinpeim** [comment]
当日、申込者のcsvを2部印刷して持っていくので、お金もらったらそのひとに✓していって、あとでその2部をmergeして突き合わせましょう。

「当日やっぱり来ちゃった///みたいな人」に関してはcsvの余白にメモしておくという感じの運用でどうでしょうか。

抜け穴としては「当日やっぱり来ちゃった///」ってやっておきながらお金を払わないマンのトラッキングができませんが、まあ、そこはみなさんの良識に任せるというので……

**Comment by keima** [comment]
良さそう、本文更新しました！

**Comment by uzulla** [comment]
- カード決済手数料後出し
- 無断キャンセル

はあったものの、

無事に完了したのでClose
