### ISSUE TITLE
チケット関連

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#4]
ATNDとか、
なお、無料です。

チケット回り本当に面倒なのでハイパーナイスアイディアがあればぜひおしえてほしい

**Comment by uzulla** [comment]
なお、今回はQRコードなどトリッキーな運用は無い。

**Comment by hasegawa-tomoki** [comment]
無料でだとconnpass 一択だったりしませんか？
集客が優れている気がする。（気のせいかなあ。）

**Comment by uzulla** [comment]
集客という観念でかんがえたことなかったんですが、なるほど〜〜

まあこのあたり色々考えることはあって、たとえば先着にするか抽選にするかとかそういう話もあり〼

**Comment by uzulla** [comment]
5月にconnpassを立てます。
（だれかやってくれる人立候補してくれてもいいのよ？？？

**Comment by uzulla** [comment]
https://connpass.com/event/56340/

立った！のでクローズします。
