### ISSUE TITLE
シールくらいは作りたい。

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#9]
その前に、デザインか…。

**Comment by silfsquare** [comment]
シールと聞いて。

**Comment by uzulla** [comment]
手練のシールマンだ

**Comment by uzulla** [comment]
シール、そろそろやるならやりたい。
よさんは僕のおさいふ次第だ。

- [ ] デザイン（デザイナ外注可能、予算つけます）
- [ ] 発注（すごい高くなければOK、500毎くらい？キラとかふざけたものでもいい）
- [ ] 納品（開催二週間くらい前にはゲットしたい）

だれか取り回したい人はいるだろうか。

**Comment by silfsquare** [comment]
印刷はどうにでもなるが問題はデザインだー

**Comment by uzulla** [comment]
デザイナー、依頼してみるか。
思い切ってイラストレーターに依頼とるというのが面白い気がするのだがどうか。

**Comment by kkotaro0111** [comment]
http://y8-2017-spring.hachiojipm.org/images/logo/svg/blue_banner.svg
http://y8-2017-spring.hachiojipm.org/images/logo/png@2x/blue_banner@2x.png

**Comment by uzulla** [comment]
シールなら、正方形のやつのほうがいいんじゃないのかなとおもったけどどう？

https://raw.githubusercontent.com/uzulla/y8-2017-spring/1ce2ebba596fe32b74c23ee522f8a77a211e2db8/images/logo/png/blue_icon.png

どっちでも（かっこ）いいけどｗ

**Comment by kkotaro0111** [comment]
http://y8-2017-spring.hachiojipm.org/images/logo/svg/blue_icon.svg
http://y8-2017-spring.hachiojipm.org/images/logo/png@2x/blue_icon@2x.png

澤田に渡すなら、aiの方がいいか
http://y8-2017-spring.hachiojipm.org/images/logo/y8_logo.ai

**Comment by silfsquare** [comment]
素材どうしようかなー

**Comment by kkotaro0111** [comment]
サテンで（まて

**Comment by uzulla** [comment]
なんでもよいけど、追金でユポとかできるなら、追金します。

**Comment by silfsquare** [comment]
ユポ＋PPって感じで見積もってみますー

**Comment by silfsquare** [comment]
あ、大きさどうしましょうかね？

**Comment by uzulla** [comment]
そうさな、正方形なら5cmくらいでいいんじゃないでしょうか
長方形なら7-8cmくらい？

**Comment by silfsquare** [comment]
了解です！

**Comment by uzulla** [comment]
余白をとったデザインなので、めっちゃ文字がちいさくて微妙だったらおしえてください！

**Comment by uzulla** [comment]
シール完了ですよね？クローズしておきます！！
